import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_material_design_icons/flutter_material_design_icons.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:food_app/cubit/cubit.dart';
import 'package:food_app/cubit/user_cubit.dart';
import 'package:food_app/model/models.dart';
import 'package:food_app/ui/shared/shared.dart';
import 'package:food_app/ui/widget/widgets.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:supercharged/supercharged.dart';

part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'general_page.dart';
part 'address_page.dart';
part 'main_page.dart';
part 'food_page.dart';
part 'detail_page.dart';
part 'payment_page.dart';
part 'ilustration_page.dart';
part 'order_history_page.dart';
part 'success_order_page.dart';
part 'success_sign_up_page.dart';
part 'profile_page.dart';